# followed_authors.yaml
followed_authors:followed_authors:
  - name: Tianzhen Hong
    orcid: "0000-0002-3035-2502"
    names:
      - Tianzhen Hong
      - T. Hong

  - name: Wei Wang
    orcid: "0000-0001-9352-6748"
    names:
      - Wei Wang
      - W. Wang

  - name: Benjamin Bechtel
    orcid: "0000-0003-2351-4480"
    names:
      - Benjamin Bechtel
      - B. Bechtel

  - name: Matthias Demuzere
    orcid: "0000-0003-1304-7353"
    names:
      - Matthias Demuzere
      - M. Demuzere

  - name: Stewart Barr
    orcid: "0000-0001-8674-449X"
    names:
      - Stewart Barr
      - S. Barr

  - name: Darren Robinson
    orcid: "0000-0001-6414-5294"
    names:
      - Darren Robinson
      - D. Robinson

  - name: Christoph Reinhart
    orcid: "0000-0002-0344-7043"
    names:
      - Christoph Reinhart
      - C. Reinhart

  - name: Ali Malkawi
    orcid: "0000-0002-4995-8478"
    names:
      - Ali Malkawi
      - A. Malkawi

  - name: Andreas Matzarakis
    orcid: "0000-0002-3117-8000"
    names:
      - Andreas Matzarakis
      - A. Matzarakis

  - name: J. Alstan Jakubiec
    orcid: "0000-0001-8579-8019"
    names:
      - Alstan Jakubiec
      - J. Alstan Jakubiec
      - A. Jakubiec

  - name: Alberto Martilli
    orcid: "0000-0001-7281-8653"
    names:
      - Alberto Martilli
      - A. Martilli

  - name: Dev Millstein
    orcid: "0000-0003-0157-8822"
    names:
      - Dev Millstein
      - D. Millstein

  - name: Da Yan
    orcid: "0000-0003-2399-723X"
    names:
      - Da Yan
      - D. Yan

  - name: Zhonghua Gou
    orcid: "0000-0002-3477-8219"
    names:
      - Zhonghua Gou
      - Z. Gou
